# Based on:
# https://github.com/josephwright/siunitx/blob/main/.github/workflows/main.yaml
# https://github.com/zauguin/install-texlive
# https://github.com/moewew/biblatex-ext/blob/dev/.github/workflows/l3build.yml

name: CI l3build tests

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  ZC_PACKAGE_LIST: |
    # The test framework
    l3build
    # Build formats
    latex
    latex-bin
    latex-bin-dev
    luatex
    luatexbase
    xetex
    # Fonts
    metafont
    mfware
    ec
    amsfonts
    mathpazo
    psnfss
    # Dependencies
    alphalph
    amsmath
    appendix
    babel-english
    babel-french
    babel-german
    babel-latin
    babel-portuges
    babel-spanish
    bookmark
    booktabs
    breqn
    caption
    carlisle
    colortbl
    csquotes
    dvips
    enumitem
    epstopdf-pkg
    etexcmds
    fancyvrb
    float
    floatrow
    graphics
    hologo
    hypdoc
    hyperref
    hyphen-french
    hyphen-german
    hyphen-latin
    iftex
    infwarerr
    intcalc
    koma-script
    kvdefinekeys
    kvoptions
    kvsetkeys
    listings
    ltxcmds
    makeindex
    mathtools
    memoir
    mptopdf
    newfloat
    oberdiek
    pdftexcmds
    polyglossia
    subfig
    tools
    trivfloat
    underscore
    zref
    zref-check

jobs:
  check:
    name: Regression tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate unique ID
        id: get-id
        run: |
          echo -n ::set-output name=id::
          cat /proc/sys/kernel/random/uuid
      - name: Load cache
        uses: actions/cache@v2
        with:
          path: ~/texlive
          key: texlive-v0-${{ steps.get-id.outputs.id }}
          restore-keys: texlive-v0-
      - name: Install TeX Live
        uses: zauguin/install-texlive@v1
        with:
          packages: ${{ env.ZC_PACKAGE_LIST }}
      - name: Run tests
        run: l3build check -q -H --show-log-on-error

  doc:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Generate unique ID
        id: get-id
        run: |
          echo -n ::set-output name=id::
          cat /proc/sys/kernel/random/uuid
      - name: Load cache
        uses: actions/cache@v2
        with:
          path: ~/texlive
          key: texlive-v0-${{ steps.get-id.outputs.id }}
          restore-keys: texlive-v0-
      - name: Install TeX Live
        uses: zauguin/install-texlive@v1
        with:
          packages: ${{ env.ZC_PACKAGE_LIST }}
      - name: Compile documentation
        run: l3build doc -q -H
